"""Tenpai PUSH/FOLD paired source producer and pilot (lisjong-arena#476).

Writes the lisbun/lisjong#288 wire contract (lisjong
``docs/tenpai-push-fold-source.md``): for every gate decision of a Champion
self-play hanchan on lisjong-engine, the decider's round result when it pushes
(the control) and, when a fold candidate exists, when it discards ``a_fold``
at that decision only.

- Control: Champion x4.  Every selector call's Champion ``PolicyDecision`` goes
  to lisjong's ``evaluate_tenpai_gate()``; a non-``None`` result is a gate
  decision.  Arena implements no gate condition and picks no candidate.
- Fold side: per gate decision with ``has_fold_candidate``, the same seed is
  played again from the start with the decider's seat replaced by lisjong's
  ``TenpaiPushFoldPairPolicy``, and stopped when that round is settled.  Arena
  never substitutes an action itself.
- Determinism: every selector call of a fold-side run up to the target must be
  the control's (same ``DecisionContext``, same action), and the target call
  must return ``a_fold``.  A difference, or a target that never appears, stops
  the generation; nothing is written.
- Round results are the engine's ``RoundCompletionFact`` (point deltas,
  winners, settlement transfers, tenpai seats).  Arena computes no score.
- ``decisions.jsonl`` holds only the decider's ``PolicyInput`` and legal
  actions; no file holds another seat's hand or the wall.

Output directory (new; an existing path is refused)::

    manifest.json     lisjong-tenpai-push-fold-source-manifest-v1
    decisions.jsonl   lisjong-tenpai-push-fold-decision-record-v1
    outcomes.jsonl    lisjong-tenpai-push-fold-outcome-record-v1
    generation.json   Arena evidence (counts, timing, runtime; not read by lisjong)

The three wire files depend only on the seeds, the split and the producer
revisions, so the same input regenerates them byte for byte.

``run`` is the pilot: its seeds (938000..938015), split and allocation are
fixed and no argument changes them.  ``development`` replays already RETIRED
lisjong-arena#385 seeds (931000..931999) to check the path; its output is not
a pilot result.  The production population is registered after the pilot and
is not generated by this script.

Usage::

    LISJONG_SHANTEN_BACKEND=rust python scripts/generate_tenpai_push_fold_source_476.py \\
        run --seed-ledger <live ledger> --allocation-identity <sha256> \\
        --selection <selection.json> --workers 8 --output <new directory>
    LISJONG_SHANTEN_BACKEND=rust python scripts/generate_tenpai_push_fold_source_476.py \\
        development --train 931400..931400 --valid 931401..931401 \\
        --selection <selection.json> --workers 2 --output <new directory>
    python scripts/generate_tenpai_push_fold_source_476.py check-allocation \\
        --seed-ledger <live ledger> --allocation-identity <sha256> \\
        --arena-revision <full sha>

Generated data is not committed.
"""

from __future__ import annotations

import argparse
import functools
import hashlib
import json
import os
import sys
import time
from concurrent.futures import ProcessPoolExecutor
from dataclasses import dataclass
from pathlib import Path

from lisjong.learning import tenpai_push_fold_source as wire
from lisjong.learning.errors import LearningError
from lisjong.learning.tenpai_push_fold import GateKind
from lisjong.policy_contract.action import DiscardAction
from lisjong_engine.driver import run_hanchan
from lisjong_engine.match_state import MatchState
from lisjong_engine.round_completion import RoundCompletionFact, RoundOutcomeKind
from lisjong_engine.rules import RuleSet
from lisjong_engine.seat import Seat as EngineSeat
from lisjong_engine.settlement import TransferReason
from lisjong_engine.win_context import WinMethod

from lisjong_arena import measurement_allocation_guard as guard
from lisjong_arena import seed_registry
from lisjong_arena.lisjong_engine.domain_conversion import seat_from_engine_seat
from lisjong_arena.lisjong_engine.policy_selector import build_seat_selectors

sys.path.insert(0, str(Path(__file__).resolve().parent))
import generate_hand_belief_source_255 as dev  # noqa: E402

OWNER_ISSUE = "lisbun/lisjong-arena#476"
PROTOCOL = "tenpai-push-fold-source-pilot-v1"
POPULATION = "tenpai-push-fold-source-pilot-16-hanchan"
SPLIT = "TRAIN12-VALID4"
PILOT_SEEDS = tuple(range(938000, 938016))
PILOT_SPLITS = {"train": PILOT_SEEDS[:12], "valid": PILOT_SEEDS[12:]}
USED_RANGES = (
    range(920000, 920544),  # L0.3 engine calibration / scientific
    range(931000, 932000),  # RETIRED #385 incl. every pilot
    range(932000, 932100),  # lisjong#245
    range(933000, 933400),  # lisjong#257 measurement
    range(934000, 934200),  # lisjong#258 / #259 formal test (#464)
    range(935000, 935002),  # #457 pilot
    range(936000, 936400),  # lisjong#262 ron-legal baseline (#460)
    range(937000, 937200),  # lisjong#260 formal test (#473)
)
"""Engine-domain seeds allocated before this pilot."""

DEVELOPMENT_SEEDS = range(931000, 932000)
"""The RETIRED lisjong-arena#385 population: the only seeds ``development`` plays."""

GENERATION_FILENAME = "generation.json"
GENERATION_SCHEMA = "lisjong-arena-tenpai-push-fold-source-generation-v1"
_ENGINE_SEAT = {int(seat_from_engine_seat(seat)): seat for seat in EngineSeat}


class TenpaiPushFoldProducerError(RuntimeError):
    """A precondition, a determinism check or a recorded fact failed (STOP / INVALID)."""


_E = TenpaiPushFoldProducerError


@dataclass(frozen=True)
class LisjongRuntime:
    """The lisjong-owned decisions this producer calls.

    The gate, the candidates and the fold-side action all come from lisjong;
    unit tests replace this object instead of playing the real Champion.
    """

    selection: Path

    def champion(self):
        from lisjong.policies.placement_aware_speed_call import (
            PlacementAwareSpeedCallPolicy,
        )

        return PlacementAwareSpeedCallPolicy()

    def gate(self, decision, c0_decision):
        from lisjong.learning.tenpai_push_fold import evaluate_tenpai_gate

        return evaluate_tenpai_gate(decision, c0_decision, _wait_model(self.selection))

    def fold_policy(self, fold_target):
        from lisjong.learning.tenpai_push_fold import TenpaiPushFoldPairPolicy

        return TenpaiPushFoldPairPolicy.from_selection(
            self.selection, fold_target=fold_target
        )


@functools.cache
def _wait_model(selection: Path):
    from lisjong.learning.riichi_wait_mawashi_policy import load_selected_wait_model

    return load_selected_wait_model(selection)


@dataclass(frozen=True, slots=True)
class Call:
    """One selector call; its index in the hanchan is the decision ``sequence``."""

    context: object
    action: object
    round_index: int


class _RoundSettled(Exception):
    """Stops a fold-side run once its round is settled."""


class _SeatRecorder:
    """Wraps one seat's Policy; the Policy receives the unchanged decision."""

    def __init__(self, policy, hanchan: _Hanchan) -> None:
        self._policy = policy
        self._hanchan = hanchan

    def choose_action(self, decision):
        hanchan = self._hanchan
        decided = self._policy.choose_action_with_analysis(decision)
        hanchan.observe(len(hanchan.calls), decision, decided)
        hanchan.calls.append(Call(decision, decided.action, len(hanchan.match.history)))
        return decided.action


class _Hanchan:
    """One hanchan (or its start up to a round): every selector call in the
    engine's order and each settled round's completion fact."""

    def __init__(self, seed: int, observe, stop_after_round: int | None = None):
        self.match = MatchState(seed=seed, rules=RuleSet.default())
        self.calls: list[Call] = []
        self.rounds: list[RoundCompletionFact] = []
        self.observe = observe
        self._stop_after_round = stop_after_round

    def _deliver(self, items) -> None:
        self.rounds.extend(
            item for item in items if isinstance(item, RoundCompletionFact)
        )
        if (
            self._stop_after_round is not None
            and len(self.rounds) > self._stop_after_round
        ):
            raise _RoundSettled

    def play(self, policies: dict) -> None:
        selectors = build_seat_selectors(
            {seat: _SeatRecorder(policy, self) for seat, policy in policies.items()}
        )
        try:
            run_hanchan(self.match, selectors, on_delivery=self._deliver)
        except _RoundSettled:
            pass


def play_control(seed: int, runtime) -> tuple[_Hanchan, list[tuple[int, object]]]:
    """Champion x4; returns the hanchan and ``(sequence, gate)`` in sequence order."""
    gates: list[tuple[int, object]] = []

    def observe(sequence, decision, decided) -> None:
        gate = runtime.gate(decision, decided)
        if gate is not None:
            gates.append((sequence, gate))

    hanchan = _Hanchan(seed, observe)
    hanchan.play({seat: runtime.champion() for seat in EngineSeat})
    if len(hanchan.rounds) != len(hanchan.match.history):
        raise _E(f"seed {seed}: a settled round has no completion fact")
    return hanchan, gates


def gate_records(seed: int, calls, gates) -> list[wire.GateDecisionRecord]:
    """The wire records of one hanchan's gate decisions; ``ordinal`` is their order."""
    records = []
    for ordinal, (sequence, gate) in enumerate(gates):
        call = calls[sequence]
        if gate.c0_action != call.action:
            raise _E(f"seed {seed} sequence {sequence}: C0 is not the control's action")
        records.append(
            wire.GateDecisionRecord(
                key=wire.GateDecisionKey(
                    seed=seed,
                    sequence=sequence,
                    seat=int(call.context.input.self_seat),
                ),
                ordinal=ordinal,
                policy_input=call.context.input,
                legal_actions=call.context.legal_actions,
                kind=gate.kind,
                riichi_seat=gate.riichi_seat,
                c0_action=gate.c0_action,
                push_action=gate.push_action,
                fold_action=gate.fold_action,
                push_ron_legal_raw=gate.push_ron_legal_raw,
                fold_ron_legal_raw=gate.fold_ron_legal_raw,
            )
        )
    return records


def play_fold(record: wire.GateDecisionRecord, control_calls, runtime) -> _Hanchan:
    """Replay the seed with the decider folding at ``record`` only, to the round end.

    Every call up to the target must be the control's and the target call must
    return ``a_fold``; otherwise the run is not the same position and fails.
    """
    key = record.key
    target = key.sequence
    context = f"seed {key.seed} gate sequence {target}"

    def observe(sequence, decision, decided) -> None:
        if sequence > target:
            return
        expected = control_calls[sequence]
        if decision != expected.context:
            raise _E(f"{context}: call {sequence} input differs from the control")
        wanted = record.fold_action if sequence == target else expected.action
        if decided.action != wanted:
            raise _E(f"{context}: call {sequence} chose {decided.action}, not {wanted}")

    round_index = control_calls[target].round_index
    hanchan = _Hanchan(key.seed, observe, stop_after_round=round_index)
    decider = _ENGINE_SEAT[key.seat]
    hanchan.play(
        {
            seat: (
                runtime.fold_policy(record.decision)
                if seat is decider
                else runtime.champion()
            )
            for seat in EngineSeat
        }
    )
    if len(hanchan.calls) <= target or len(hanchan.rounds) != round_index + 1:
        raise _E(f"{context}: the fold target did not appear before the round ended")
    return hanchan


def _base_points(transfers) -> int:
    """Win / payment points without honba (riichi sticks are never a transfer)."""
    return sum(
        transfer.amount
        for transfer in transfers
        if transfer.reason is not TransferReason.HONBA
    )


def round_outcome(
    record: wire.GateDecisionRecord, side: str, calls, fact: RoundCompletionFact
) -> wire.RoundOutcome:
    """The decider's result of the gate decision's round, from the engine's facts.

    ``calls`` are the selector calls of the run that produced ``fact``.  On a
    multiple ron of the decider's discard, ``deal_in`` names the winner nearest
    to the decider in turn order and holds the decider's whole payment.
    """
    key = record.key
    context = f"seed {key.seed} sequence {key.sequence} {side}"
    riichi_push = side == wire.PUSH and record.kind is GateKind.RIICHI
    index = key.sequence + 1 if riichi_push else key.sequence
    round_index = calls[key.sequence].round_index
    if index >= len(calls):
        raise _E(f"{context}: the round has no declaration discard")
    discard = calls[index]
    expected = record.fold_action if side == wire.FOLD else record.c0_action
    if (
        not isinstance(discard.action, DiscardAction)
        or int(discard.context.input.self_seat) != key.seat
        or discard.round_index != round_index
        or (not riichi_push and discard.action != expected)
        or (riichi_push and calls[key.sequence].action != expected)
    ):
        raise _E(f"{context}: the recorded call is not this side's discard")

    seat = _ENGINE_SEAT[key.seat]
    won = fact.outcome is RoundOutcomeKind.WIN
    dealt_in = (
        won and fact.winners[0].win_method is WinMethod.RON and fact.source_seat is seat
    )
    acted_later = any(
        call.round_index == round_index
        and int(call.context.input.self_seat) == key.seat
        for call in calls[index + 1 :]
    )
    winner = next((w for w in fact.winners if w.seat is seat), None)
    win_method = win_points = deal_in_to = deal_in_points = None
    if winner is not None:
        win_method = winner.win_method.value
        win_points = _base_points(
            t for t in fact.settlement_transfers if t.recipient is seat
        )
    if dealt_in:
        winners = {w.seat for w in fact.winners}
        nearest = seat.next()
        while nearest not in winners:
            nearest = nearest.next()
        deal_in_to = seat_from_engine_seat(nearest)
        deal_in_points = _base_points(
            t for t in fact.settlement_transfers if t.payer is seat
        )
    return wire.RoundOutcome(
        key=key,
        side=side,
        round_delta=next(d.delta for d in fact.point_deltas if d.seat is seat),
        # The decider's last tile-releasing call of a round it deals into is the
        # ronned one: any later discard or kan would be a later call.
        discard_passed=not (dealt_in and not acted_later),
        win_method=win_method,
        win_points=win_points,
        deal_in_to=deal_in_to,
        deal_in_points=deal_in_points,
        exhaustive_draw_tenpai=(
            seat in fact.tenpai_seats
            if fact.outcome is RoundOutcomeKind.EXHAUSTIVE_DRAW
            else None
        ),
        declaration_discard=discard.action if riichi_push else None,
    )


def play_seed(seed: int, runtime) -> dict[str, object]:
    """One control hanchan and its fold-side runs: the wire rows and the counts."""
    started = time.perf_counter()
    control, gates = play_control(seed, runtime)
    control_seconds = time.perf_counter() - started
    counts = {
        kind.value: {"gate_decisions": 0, "with_fold_candidate": 0} for kind in GateKind
    }
    declaration = {"match": 0, "mismatch": 0}
    decisions, outcomes = [], []
    fold_runs = fold_calls = multiple_ron_deal_ins = 0
    started = time.perf_counter()
    for record in gate_records(seed, control.calls, gates):
        fact = control.rounds[control.calls[record.key.sequence].round_index]
        sides = [(round_outcome(record, wire.PUSH, control.calls, fact), fact)]
        counts[record.kind.value]["gate_decisions"] += 1
        if record.kind is GateKind.RIICHI:
            matched = sides[0][0].declaration_discard == record.push_action
            declaration["match" if matched else "mismatch"] += 1
        if record.has_fold_candidate:
            counts[record.kind.value]["with_fold_candidate"] += 1
            fold = play_fold(record, control.calls, runtime)
            fold_runs += 1
            fold_calls += len(fold.calls)
            sides.append(
                (
                    round_outcome(record, wire.FOLD, fold.calls, fold.rounds[-1]),
                    fold.rounds[-1],
                )
            )
        decisions.append(dev.canonical_line(wire.decision_to_value(record)))
        for outcome, side_fact in sides:
            multiple_ron_deal_ins += (
                outcome.deal_in_to is not None and len(side_fact.winners) > 1
            )
            outcomes.append(dev.canonical_line(wire.outcome_to_value(outcome)))
    return {
        "seed": seed,
        "decisions": decisions,
        "outcomes": outcomes,
        "stats": {
            "seed": seed,
            "rounds": len(control.rounds),
            "control_calls": len(control.calls),
            "gate_decisions": counts,
            "riichi_declaration_prediction": declaration,
            "multiple_ron_deal_ins": multiple_ron_deal_ins,
            "fold_runs": fold_runs,
            "fold_calls": fold_calls,
            "control_seconds": round(control_seconds, 3),
            "fold_seconds": round(time.perf_counter() - started, 3),
        },
    }


def write_source(
    output: Path,
    *,
    splits: dict[str, tuple[int, ...]],
    games: list[dict[str, object]],
    producer: dict[str, str],
) -> dict[str, dict[str, object]]:
    """Write the three wire files and read them back with lisjong's strict reader."""
    seeds = sorted(seed for name in wire.SPLITS for seed in splits[name])
    by_seed = {game["seed"]: game for game in games}
    if len(by_seed) != len(games) or sorted(by_seed) != seeds:
        raise _E("the games do not match the split seeds")
    output.mkdir(parents=True, exist_ok=False)
    files = {}
    for name, filename in (
        ("decisions", wire.DECISIONS_FILENAME),
        ("outcomes", wire.OUTCOMES_FILENAME),
    ):
        lines = [line for seed in seeds for line in by_seed[seed][name]]
        data = "".join(lines).encode("utf-8")
        (output / filename).write_bytes(data)
        files[name] = {
            "bytes": len(data),
            "rows": len(lines),
            "sha256": hashlib.sha256(data).hexdigest(),
        }
    (output / wire.MANIFEST_FILENAME).write_bytes(
        wire.manifest_text(producer=producer, splits=splits, files=files).encode(
            "utf-8"
        )
    )
    _, pairs = wire.read_source(output)
    if len(pairs) != files["decisions"]["rows"] or (
        len(pairs) + sum(pair.fold is not None for pair in pairs)
        != files["outcomes"]["rows"]
    ):
        raise _E("the written source does not read back as the generated pairs")
    return files


def _total(stats: list[dict[str, object]]) -> dict[str, object]:
    kinds = {
        kind.value: {
            name: sum(item["gate_decisions"][kind.value][name] for item in stats)
            for name in ("gate_decisions", "with_fold_candidate")
        }
        for kind in GateKind
    }
    return {
        "hanchan": len(stats),
        "gate_decisions": kinds,
        "riichi_declaration_prediction": {
            name: sum(item["riichi_declaration_prediction"][name] for item in stats)
            for name in ("match", "mismatch")
        },
        "multiple_ron_deal_ins": sum(item["multiple_ron_deal_ins"] for item in stats),
        "fold_runs": sum(item["fold_runs"] for item in stats),
        "seconds_per_hanchan": round(
            sum(item["control_seconds"] + item["fold_seconds"] for item in stats)
            / len(stats),
            3,
        ),
    }


def generate(
    output: Path,
    *,
    splits: dict[str, tuple[int, ...]],
    producer: dict[str, str],
    runtime,
    workers: int,
    evidence: dict[str, object],
) -> dict[str, object]:
    """Play every seed, write the source and its ``generation.json``."""
    if output.exists():
        raise _E(f"refusing to overwrite {output}")
    seeds = [seed for name in wire.SPLITS for seed in splits[name]]
    if not seeds or len(set(seeds)) != len(seeds):
        raise _E("splits must hold distinct seeds")
    started = time.perf_counter()
    play = functools.partial(play_seed, runtime=runtime)
    if workers == 1:
        games = [play(seed) for seed in seeds]
    else:
        with ProcessPoolExecutor(workers) as executor:
            games = list(executor.map(play, seeds))
    files = write_source(output, splits=splits, games=games, producer=producer)
    stats = [game["stats"] for game in sorted(games, key=lambda game: game["seed"])]
    document = {
        "schema": GENERATION_SCHEMA,
        **evidence,
        "producer": producer,
        "splits": {name: list(splits[name]) for name in wire.SPLITS},
        "workers": workers,
        "wall_seconds": round(time.perf_counter() - started, 3),
        "files": {
            **files,
            "manifest": guard.file_digest(output / wire.MANIFEST_FILENAME),
        },
        "total": _total(stats),
        "games": stats,
    }
    guard.write_new(
        output / GENERATION_FILENAME,
        json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
    )
    return document


def allocation_preset() -> guard.AllocationPreset:
    """The pilot's fixed allocation preset; no argument changes it."""
    return guard.AllocationPreset(
        owner_issue=OWNER_ISSUE,
        protocol=PROTOCOL,
        seed_domain=seed_registry.LISJONG_ENGINE_HANCHAN_SEED_DOMAIN,
        population=POPULATION,
        split=SPLIT,
        seeds=PILOT_SEEDS,
        splits=tuple(PILOT_SPLITS.items()),
        split_sizes=(12, 4),
        used_ranges=USED_RANGES,
    )


def check_allocation(
    seed_ledger: Path, allocation_identity: str, arena_revision: str
) -> dict[str, object]:
    """Resolve the pilot allocation against the live ledger (no game is played)."""
    try:
        ledger = guard.load_live_ledger(seed_ledger)
        binding, record = guard.authorize(
            ledger,
            allocation_identity,
            allocation_preset(),
            arena_revision=arena_revision,
        )
    except guard.AllocationGuardError as error:
        raise _E(str(error)) from error
    return {
        "allocation_binding": binding,
        "allocation": record,
        "ledger_revision": seed_registry.ledger_revision(ledger),
    }


def native_runtime(selection: Path) -> dict[str, object]:
    """The scorer, shanten backend and wait model the gate needs (fails closed)."""
    from lisjong.hand_evaluation.scoring import require_scoring_backend

    if os.environ.get("LISJONG_SHANTEN_BACKEND") != "rust":
        raise _E("generation requires LISJONG_SHANTEN_BACKEND=rust")
    require_scoring_backend()
    import _lisjong_native

    if _lisjong_native.SOURCE_REVISION != dev._revision("lisjong"):
        raise _E("the native scorer was not built from the installed lisjong")
    _wait_model(selection)
    return {
        "python": ".".join(map(str, sys.version_info[:3])),
        "shanten_backend": "rust",
        "native_source_revision": _lisjong_native.SOURCE_REVISION,
    }


def current_producer(selection: Path) -> dict[str, str]:
    """The manifest ``producer``: the revisions and the wait model that really run."""
    return {
        "arena_revision": dev._arena_revision(),
        "lisjong_engine_revision": dev._revision("lisjong-engine"),
        "lisjong_revision": dev._revision("lisjong"),
        "policy": dev.POLICY,
        "wait_model_sha256": guard.file_digest(selection)["sha256"],
    }


def run_pilot(arguments) -> dict[str, object]:
    from lisjong_arena.policy_source_record import binding as runtime_identity

    native = native_runtime(arguments.selection)
    producer = current_producer(arguments.selection)
    allocation = check_allocation(
        arguments.seed_ledger,
        arguments.allocation_identity,
        producer["arena_revision"],
    )
    pinned = runtime_identity.runtime_binding(
        Path(__file__).resolve().parents[1] / "pyproject.toml"
    )
    if pinned["arena_revision"] != producer["arena_revision"]:
        raise _E("the executing checkout is not clean")
    return generate(
        arguments.output,
        splits=PILOT_SPLITS,
        producer=producer,
        runtime=LisjongRuntime(arguments.selection),
        workers=arguments.workers,
        evidence={
            "owner_issue": OWNER_ISSUE,
            "protocol": PROTOCOL,
            "population": POPULATION,
            "runtime": {**native, "dependencies": pinned["dependencies"]},
            **allocation,
        },
    )


def run_development(arguments) -> dict[str, object]:
    splits = {"train": tuple(arguments.train), "valid": tuple(arguments.valid)}
    if any(seed not in DEVELOPMENT_SEEDS for name in splits for seed in splits[name]):
        raise _E("development seeds must be RETIRED #385 seeds 931000..931999")
    return generate(
        arguments.output,
        splits=splits,
        producer=current_producer(arguments.selection),
        runtime=LisjongRuntime(arguments.selection),
        workers=arguments.workers,
        evidence={
            "owner_issue": OWNER_ISSUE,
            "protocol": "development-check",
            "runtime": native_runtime(arguments.selection),
        },
    )


def _seed_list(text: str) -> list[int]:
    first, _, last = text.partition("..")
    try:
        return list(range(int(first), int(last or first) + 1))
    except ValueError as error:
        raise argparse.ArgumentTypeError("seeds must be <first>[..<last>]") from error


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    commands = parser.add_subparsers(dest="command", required=True)
    run_parser = commands.add_parser("run", help="the fixed 16-hanchan pilot")
    development = commands.add_parser(
        "development", help="replay RETIRED #385 seeds to check the path"
    )
    development.add_argument("--train", type=_seed_list, required=True)
    development.add_argument("--valid", type=_seed_list, required=True)
    for command in (run_parser, development):
        command.add_argument("--selection", type=Path, required=True)
        command.add_argument("--workers", type=int, default=1)
        command.add_argument("--output", type=Path, required=True)
    check = commands.add_parser(
        "check-allocation", help="no-game authorization check of the allocation"
    )
    check.add_argument("--arena-revision", required=True)
    for command in (run_parser, check):
        command.add_argument("--seed-ledger", type=Path, required=True)
        command.add_argument("--allocation-identity", required=True)
    return parser


def main(argv=None) -> int:
    from lisjong.hand_evaluation.scoring import ScoringBackendUnavailableError

    from lisjong_arena.policy_source_record import PolicySourceRecordError

    arguments = build_parser().parse_args(argv)
    try:
        if arguments.command == "check-allocation":
            result = check_allocation(
                arguments.seed_ledger,
                arguments.allocation_identity,
                arguments.arena_revision,
            )
        else:
            if arguments.workers < 1:
                raise _E("workers must be positive")
            document = (
                run_pilot(arguments)
                if arguments.command == "run"
                else run_development(arguments)
            )
            result = {key: document[key] for key in ("files", "total", "wall_seconds")}
        print(json.dumps(result, indent=2, sort_keys=True))
        return 0
    except (
        TenpaiPushFoldProducerError,
        PolicySourceRecordError,
        LearningError,
        ScoringBackendUnavailableError,
        wire.TenpaiPushFoldSourceError,
    ) as error:
        print(f"STOP / INVALID: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
