"""Stage 4a Gate 0: candidate generation -> retention -> strict readback。

```text
locked generation population (TRAIN 200..209 / VALIDATION 210..212)
    -> Stage 2 locked model / training config
    -> Stage 4a candidate bundle (operator-declared non-ephemeral root配下)
        <retention root>/<retention key>/
            checkpoint/            exact retained weights + manifest
            candidate-freeze.json  Stage 4a-owned freeze record
    -> strict loader readback
    -> freeze record binding (identity / digest / bytes / schema)
```

**checkpoint format reuse**: on-diskのcheckpoint directory formatと、その
strict loaderはStage 3が確立したimplementation primitiveをそのまま使う
(`lisbun/lisjong-arena #138`が明示的に許すminimal path)。Stage 4a固有の
freeze identity / purposeはこのmoduleが所有する`candidate-freeze.json`が
持ち、checkpoint側のschemaを再設計しない。

したがって次を混同しない。

- **historical Stage 3 fixture**: serving integration専用のhistorical artifact。
  Stage 4aはこれをstrength evidenceへaliasしない
- **Stage 4a candidate**: このmoduleがGate 0で新規生成し、freeze recordで
  purposeとidentityを宣言し、non-ephemeral locationへretainしたbundle

candidate identityは`learned-stage4a:<checkpoint identity>`であり、strict
loadしたcheckpoint identityから機械的に導出する。free-form aliasを与える
入口を持たない。

**durability boundary**: 実際のstorage durabilityはcaller / operatorの宣言で
ある。このmoduleが機械的にfail closedできるのは「temporary directoryでない」
「Git work tree内でない」「既存destinationを上書きしない」までであり、
declared backendはfreeze recordへそのまま記録して監査可能にする。宣言できる
non-ephemeral rootが無い場合、callerは`Stage4aRetentionError`のまま
`ARTIFACT RETENTION BLOCKED`として停止する。
"""

import re
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from lisjong_arena._artifact_io import (
    canonical_json_text,
    read_json_document,
    write_new_artifact_file,
)
from lisjong_arena.learned_policy_stage2.artifact import feature_block, vocabulary_block
from lisjong_arena.learned_policy_stage2.training import (
    locked_model_block,
    locked_training_block,
)
from lisjong_arena.learned_policy_stage3.artifact import (
    ServingCheckpoint,
    load_serving_checkpoint,
)
from lisjong_arena.learned_policy_stage3.fixture import build_fixture_checkpoint

from .errors import Stage4aFreezeError, Stage4aRetentionError
from .protocol import (
    CANDIDATE_GENERATION_TRAIN_SEEDS,
    CANDIDATE_GENERATION_VALIDATION_SEEDS,
    EXCLUDED_STAGE2_TEST_SEEDS,
    EXCLUDED_STAGE3_SERVING_SEEDS,
    PROTOCOL_ID,
    derive_candidate_identity,
    require_candidate_generation_seed,
)

BUNDLE_CHECKPOINT_DIRNAME = "checkpoint"
FREEZE_RECORD_FILENAME = "candidate-freeze.json"
FREEZE_RECORD_SCHEMA_VERSION = "arena-learned-policy-stage4a-candidate-freeze-v1"
CANDIDATE_PURPOSE = "stage4a-bounded-strength-screening-candidate"

CHECKPOINT_FORMAT_NOTE = (
    "The Stage 3 serving checkpoint directory format and its strict loader are "
    "reused as implementation primitives. This bundle is a Stage 4a candidate "
    "generated by the Stage 4a Gate 0 path from TRAIN 200..209 and VALIDATION "
    "210..212 under the Stage 2 locked protocol; it is not an alias of any "
    "historical Stage 3 artifact. No strength claim is carried by this "
    "checkpoint: Stage 4a strength evidence lives only in the ABBB "
    "SingleRoundStrengthArtifact files."
)

_KEY_SEGMENT = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*").fullmatch

_FREEZE_FIELDS = {
    "freeze_record_schema_version",
    "protocol_id",
    "purpose",
    "candidate_identity",
    "checkpoint",
    "generation",
    "source_revisions",
    "retention",
    "strength_claim",
}
_CHECKPOINT_FIELDS = {
    "schema_version",
    "identity",
    "dataset_identity",
    "weights_sha256",
    "weights_bytes",
    "parameter_count",
    "selected_epoch",
    "selected_validation_choice_masked_ce",
    "feature",
    "vocabulary",
    "model",
    "training",
    "format_note",
}
_GENERATION_FIELDS = {
    "train_seeds",
    "validation_seeds",
    "excluded_stage2_test_seeds",
    "excluded_stage3_serving_seeds",
    "teacher_identity",
    "teacher_source_revision",
    "row_count",
}
_RETENTION_FIELDS = {"backend", "key", "checkpoint_relative_path"}


def _ephemeral_roots() -> tuple[Path, ...]:
    """final retentionとして扱わないtemporary rootの集合。"""
    roots = [Path(tempfile.gettempdir()), Path("/tmp"), Path("/var/tmp")]
    return tuple(dict.fromkeys(root.resolve() for root in roots if root.exists()))


def _is_within(path: Path, parent: Path) -> bool:
    return path == parent or parent in path.parents


def _git_work_tree_root(path: Path) -> Path | None:
    """``path``自身または祖先にGit work treeがあればそのrootを返す。"""
    for candidate in (path, *path.parents):
        if (candidate / ".git").exists():
            return candidate
    return None


@dataclass(frozen=True, slots=True)
class RetentionTarget:
    """operatorが宣言したnon-ephemeral retention先。

    ``root``はmachine-localなabsolute pathなので、public Issueやfreeze
    recordへはlogicalな``backend`` / ``key``だけを出す。
    """

    backend: str
    root: Path
    key: str

    @property
    def bundle_path(self) -> Path:
        return self.root / self.key

    @property
    def checkpoint_path(self) -> Path:
        return self.bundle_path / BUNDLE_CHECKPOINT_DIRNAME

    @property
    def freeze_record_path(self) -> Path:
        return self.bundle_path / FREEZE_RECORD_FILENAME

    def to_document(self) -> dict[str, Any]:
        """freeze recordへ記録するlogical retention referenceを返す。"""
        return {
            "backend": self.backend,
            "key": self.key,
            "checkpoint_relative_path": f"{self.key}/{BUNDLE_CHECKPOINT_DIRNAME}",
        }


def resolve_retention_target(
    *, backend: object, root: object, key: object
) -> RetentionTarget:
    """retention先をfail closedで解決する。

    機械的に確認するのは次だけである。

    - declared backendが非空のexplicit identityであること
    - rootが実在するabsolute directoryであること
    - rootがtemporary directory配下でないこと
    - rootがGit work tree内でないこと(repositoryへweightsを置かない)
    - bundle destinationがまだ存在しないこと(write-once)

    storage自体のdurabilityはここでは証明できない。declared backendを
    freeze recordへ記録し、監査可能にすることで代替する。
    """
    if type(backend) is not str or not backend.strip():
        raise Stage4aRetentionError(
            "an explicit non-empty retention backend identity is required"
        )
    if type(key) is not str or not key:
        raise Stage4aRetentionError("an explicit retention key is required")
    segments = key.split("/")
    if any(_KEY_SEGMENT(segment) is None for segment in segments):
        raise Stage4aRetentionError(f"invalid retention key: {key!r}")

    if not isinstance(root, (str, Path)):
        raise Stage4aRetentionError("retention root must be a path")
    root_path = Path(root)
    if not root_path.is_absolute():
        raise Stage4aRetentionError("retention root must be an absolute path")
    if not root_path.is_dir():
        raise Stage4aRetentionError(
            "retention root does not exist as a directory; a non-ephemeral "
            "location must already be provisioned by the operator"
        )
    root_path = root_path.resolve()

    for ephemeral in _ephemeral_roots():
        if _is_within(root_path, ephemeral):
            raise Stage4aRetentionError(
                "a temporary directory is not a non-ephemeral retention location"
            )
    work_tree = _git_work_tree_root(root_path)
    if work_tree is not None:
        raise Stage4aRetentionError(
            "the retention root is inside a Git work tree; generated weights and "
            "evaluation artifacts must not be placed in a repository"
        )

    target = RetentionTarget(backend=backend, root=root_path, key=key)
    if target.bundle_path.exists():
        raise Stage4aRetentionError(
            "retention destination already exists; an existing candidate bundle "
            "is never overwritten"
        )
    return target


@dataclass(frozen=True, slots=True)
class Stage4aFreeze:
    """Stage 4a candidateのfreeze record。"""

    document: dict

    @property
    def candidate_identity(self) -> str:
        return self.document["candidate_identity"]

    @property
    def checkpoint_identity(self) -> str:
        return self.document["checkpoint"]["identity"]

    @property
    def checkpoint_schema_version(self) -> str:
        return self.document["checkpoint"]["schema_version"]

    @property
    def dataset_identity(self) -> str:
        return self.document["checkpoint"]["dataset_identity"]

    @property
    def weights_sha256(self) -> str:
        return self.document["checkpoint"]["weights_sha256"]

    @property
    def weights_bytes(self) -> int:
        return self.document["checkpoint"]["weights_bytes"]

    @property
    def retention_backend(self) -> str:
        return self.document["retention"]["backend"]

    @property
    def retention_key(self) -> str:
        return self.document["retention"]["key"]

    def to_document(self) -> dict[str, Any]:
        return dict(self.document)


def _expect_object(value: object, fields: set, context: str) -> dict:
    if type(value) is not dict or set(value) != fields:
        raise Stage4aFreezeError(f"freeze record {context} fields are invalid")
    return value


def _expect_str(value: object, context: str) -> str:
    if type(value) is not str or not value:
        raise Stage4aFreezeError(f"freeze record {context} must be a non-empty string")
    return value


def _expect_int_list(value: object, context: str) -> list:
    if type(value) is not list or any(type(item) is not int for item in value):
        raise Stage4aFreezeError(f"freeze record {context} must be an integer array")
    return value


def parse_freeze_document(value: object) -> Stage4aFreeze:
    """freeze documentをfail closedで検証する。

    missing / unknown fieldとschema・purpose・protocol mismatchを受理しない。
    candidate identityはcheckpoint identityからの導出値と一致しなければ
    ならず、free-form aliasをここで通さない。
    """
    document = _expect_object(value, _FREEZE_FIELDS, "root")
    if document["freeze_record_schema_version"] != FREEZE_RECORD_SCHEMA_VERSION:
        raise Stage4aFreezeError("unsupported freeze record schema version")
    if document["protocol_id"] != PROTOCOL_ID:
        raise Stage4aFreezeError("freeze record protocol_id is not the Stage 4a one")
    if document["purpose"] != CANDIDATE_PURPOSE:
        raise Stage4aFreezeError("freeze record purpose is not the Stage 4a one")
    if document["strength_claim"] is not None:
        raise Stage4aFreezeError("a freeze record must not carry a strength claim")

    checkpoint = _expect_object(
        document["checkpoint"], _CHECKPOINT_FIELDS, "checkpoint"
    )
    for name in (
        "schema_version",
        "identity",
        "dataset_identity",
        "weights_sha256",
        "format_note",
    ):
        _expect_str(checkpoint[name], f"checkpoint.{name}")
    for name in ("weights_bytes", "parameter_count", "selected_epoch"):
        if type(checkpoint[name]) is not int:
            raise Stage4aFreezeError(f"freeze record checkpoint.{name} must be an int")
    if checkpoint["feature"] != feature_block():
        raise Stage4aFreezeError("freeze record feature block is not the locked one")
    if checkpoint["vocabulary"] != vocabulary_block():
        raise Stage4aFreezeError("freeze record vocabulary block is not the locked one")
    if checkpoint["model"] != locked_model_block():
        raise Stage4aFreezeError("freeze record model config is not the locked one")
    if checkpoint["training"] != locked_training_block():
        raise Stage4aFreezeError("freeze record training config is not the locked one")

    generation = _expect_object(
        document["generation"], _GENERATION_FIELDS, "generation"
    )
    for name in ("train_seeds", "validation_seeds"):
        for seed in _expect_int_list(generation[name], f"generation.{name}"):
            require_candidate_generation_seed(seed)
    if generation["train_seeds"] != list(CANDIDATE_GENERATION_TRAIN_SEEDS):
        raise Stage4aFreezeError("freeze record TRAIN population is not the locked one")
    if generation["validation_seeds"] != list(CANDIDATE_GENERATION_VALIDATION_SEEDS):
        raise Stage4aFreezeError(
            "freeze record VALIDATION population is not the locked one"
        )
    if generation["excluded_stage2_test_seeds"] != list(EXCLUDED_STAGE2_TEST_SEEDS):
        raise Stage4aFreezeError("freeze record Stage 2 TEST exclusion is invalid")
    if generation["excluded_stage3_serving_seeds"] != list(
        EXCLUDED_STAGE3_SERVING_SEEDS
    ):
        raise Stage4aFreezeError("freeze record Stage 3 smoke exclusion is invalid")
    _expect_str(generation["teacher_identity"], "generation.teacher_identity")
    _expect_str(
        generation["teacher_source_revision"], "generation.teacher_source_revision"
    )
    if type(generation["row_count"]) is not int or generation["row_count"] <= 0:
        raise Stage4aFreezeError("freeze record generation.row_count must be positive")

    revisions = document["source_revisions"]
    if type(revisions) is not dict or not revisions:
        raise Stage4aFreezeError("freeze record source_revisions are invalid")
    for name in (
        "lisjong_arena_revision",
        "lisjong_revision",
        "lisjong_engine_revision",
    ):
        if name not in revisions:
            raise Stage4aFreezeError(f"freeze record source_revisions lacks {name}")
        _expect_str(revisions[name], f"source_revisions.{name}")

    retention = _expect_object(document["retention"], _RETENTION_FIELDS, "retention")
    for name in sorted(_RETENTION_FIELDS):
        _expect_str(retention[name], f"retention.{name}")

    identity = _expect_str(document["candidate_identity"], "candidate_identity")
    if identity != derive_candidate_identity(checkpoint["identity"]):
        raise Stage4aFreezeError(
            "candidate identity is not mechanically derived from the checkpoint "
            "identity"
        )
    return Stage4aFreeze(document=document)


def build_freeze_document(
    checkpoint: ServingCheckpoint, *, target: RetentionTarget
) -> dict[str, Any]:
    """retained checkpoint manifestからStage 4a freeze documentを構築する。

    生成populationはcheckpoint manifest側の宣言を正本として読み、locked
    Stage 4a populationと一致しない場合はfail closedする。held-out seedが
    generation pathへ入っていないことを、記録ではなく検証で固定する。
    """
    if not isinstance(checkpoint, ServingCheckpoint):
        raise TypeError("checkpoint must be a ServingCheckpoint")
    if not isinstance(target, RetentionTarget):
        raise TypeError("target must be a RetentionTarget")

    manifest = checkpoint.manifest
    generation = manifest.get("fixture")
    if type(generation) is not dict:
        raise Stage4aFreezeError(
            "the retained checkpoint does not declare its generation population"
        )
    document = {
        "freeze_record_schema_version": FREEZE_RECORD_SCHEMA_VERSION,
        "protocol_id": PROTOCOL_ID,
        "purpose": CANDIDATE_PURPOSE,
        "candidate_identity": derive_candidate_identity(checkpoint.identity),
        "checkpoint": {
            "schema_version": manifest["checkpoint_schema_version"],
            "identity": checkpoint.identity,
            "dataset_identity": checkpoint.dataset_identity,
            "weights_sha256": checkpoint.weights_sha256,
            "weights_bytes": manifest["weights_bytes"],
            "parameter_count": manifest["parameter_count"],
            "selected_epoch": manifest["selected_epoch"],
            "selected_validation_choice_masked_ce": manifest[
                "selected_validation_choice_masked_ce"
            ],
            "feature": dict(manifest["feature"]),
            "vocabulary": dict(manifest["vocabulary"]),
            "model": dict(manifest["model"]),
            "training": dict(manifest["training"]),
            "format_note": CHECKPOINT_FORMAT_NOTE,
        },
        "generation": {
            "train_seeds": list(generation["train_seeds"]),
            "validation_seeds": list(generation["validation_seeds"]),
            "excluded_stage2_test_seeds": list(EXCLUDED_STAGE2_TEST_SEEDS),
            "excluded_stage3_serving_seeds": list(EXCLUDED_STAGE3_SERVING_SEEDS),
            "teacher_identity": generation["teacher_identity"],
            "teacher_source_revision": generation["teacher_source_revision"],
            "row_count": generation["row_count"],
        },
        "source_revisions": dict(manifest["provenance"]),
        "retention": target.to_document(),
        "strength_claim": None,
    }
    # 書き出す前に、read側と同じstrict契約で自己検証する。
    parse_freeze_document(document)
    return document


def write_freeze_record(
    checkpoint: ServingCheckpoint, *, target: RetentionTarget
) -> Stage4aFreeze:
    """freeze recordをcanonical JSONで書き出す(既存pathは上書きしない)。"""
    document = build_freeze_document(checkpoint, target=target)
    write_new_artifact_file(target.freeze_record_path, canonical_json_text(document))
    return Stage4aFreeze(document=document)


def load_freeze_record(bundle_path: str | Path) -> Stage4aFreeze:
    """retained bundleのfreeze recordをstrict parseする。"""
    path = Path(bundle_path) / FREEZE_RECORD_FILENAME
    if not path.is_file():
        raise Stage4aFreezeError("candidate freeze record is missing")
    try:
        document = read_json_document(path)
    except Exception as error:
        raise Stage4aFreezeError("candidate freeze record is not valid JSON") from error
    return parse_freeze_document(document)


def verify_freeze_binding(freeze: Stage4aFreeze, checkpoint: ServingCheckpoint) -> None:
    """freeze recordがretained checkpointそのものへbindしていることを確認する。

    checkpointを差し替えた場合、identity / digest / byte countのいずれかが
    必ず食い違うため、ここでfail closedする。
    """
    if not isinstance(freeze, Stage4aFreeze):
        raise TypeError("freeze must be a Stage4aFreeze")
    if not isinstance(checkpoint, ServingCheckpoint):
        raise TypeError("checkpoint must be a ServingCheckpoint")
    manifest = checkpoint.manifest
    for name, frozen, actual in (
        (
            "checkpoint schema version",
            freeze.checkpoint_schema_version,
            manifest["checkpoint_schema_version"],
        ),
        ("checkpoint identity", freeze.checkpoint_identity, checkpoint.identity),
        ("dataset identity", freeze.dataset_identity, checkpoint.dataset_identity),
        ("weights sha256", freeze.weights_sha256, checkpoint.weights_sha256),
        ("weights bytes", freeze.weights_bytes, manifest["weights_bytes"]),
    ):
        if frozen != actual:
            raise Stage4aFreezeError(
                f"retained {name} does not match the freeze record: "
                f"{actual!r} != {frozen!r}"
            )
    derived = derive_candidate_identity(checkpoint.identity)
    if freeze.candidate_identity != derived:
        raise Stage4aFreezeError(
            "the frozen candidate identity is not the identity derived from the "
            "retained checkpoint"
        )


def strict_readback(bundle_path: str | Path) -> tuple[Stage4aFreeze, ServingCheckpoint]:
    """retained bundleをstrict loaderで読み直し、freeze bindingまで確認する。"""
    path = Path(bundle_path)
    freeze = load_freeze_record(path)
    checkpoint = load_serving_checkpoint(path / BUNDLE_CHECKPOINT_DIRNAME)
    verify_freeze_binding(freeze, checkpoint)
    return freeze, checkpoint


def freeze_candidate(
    target: RetentionTarget,
) -> tuple[Stage4aFreeze, ServingCheckpoint, dict]:
    """Gate 0を1本で実行する: generate -> retain -> freeze -> strict readback。

    retention先の検証は生成より前に済ませてある(``resolve_retention_target``)。
    生成後のbundleは上書きせず、strict readbackがfreeze recordとbindするまで
    Gate 0をpassさせない。
    """
    if not isinstance(target, RetentionTarget):
        raise TypeError("target must be a RetentionTarget")
    if target.bundle_path.exists():
        raise Stage4aRetentionError(
            "retention destination already exists; an existing candidate bundle "
            "is never overwritten"
        )
    checkpoint, report = build_fixture_checkpoint(target.checkpoint_path)
    write_freeze_record(checkpoint, target=target)
    freeze, retained = strict_readback(target.bundle_path)
    return freeze, retained, report


__all__ = [
    "BUNDLE_CHECKPOINT_DIRNAME",
    "CANDIDATE_PURPOSE",
    "CHECKPOINT_FORMAT_NOTE",
    "FREEZE_RECORD_FILENAME",
    "FREEZE_RECORD_SCHEMA_VERSION",
    "RetentionTarget",
    "Stage4aFreeze",
    "build_freeze_document",
    "freeze_candidate",
    "load_freeze_record",
    "parse_freeze_document",
    "resolve_retention_target",
    "strict_readback",
    "verify_freeze_binding",
    "write_freeze_record",
]
